language: python

python:
  - "3.6"
services:
  - docker

before_install:
- docker-compose -f ./Activity\ 3/docker-compose.yml down
- docker-compose -f ./Activity\ 3/docker-compose.yml up -d

script:
  - travis_wait 30 pytest test.py
