language: python

python:
  - "3.6"
services:
  - docker

before_install:
- docker-compose -f ./Activity\ 4/docker-compose.yml down
- docker-compose -f ./Activity\ 4/docker-compose.yml up -d

before_script:
- sleep 120
 
script:
- pytest test.py
