language: python

python:
  - "3.6"
services:
  - docker

before_install:
- docker-compose -f ./Activity\ 2/docker-compose.yml down
- docker-compose -f ./Activity\ 2/docker-compose.yml up -d

script:
  - pytest
