version: "3"
services:
  webapp:
    build: ./flask
    links:
      - mysql
    ports:
      - "5000:5000"

  mysql:
    build: ./sqlserver
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
