CREATE DATABASE db;

USE db;

CREATE TABLE User(
	UserID INTEGER NOT NULL AUTO_INCREMENT,
	Username VARCHAR(30) NOT NULL,
	EncryptedPass VARCHAR(64) NOT NULL,
	TotalVideoCount INTEGER,
	DateCreated DATE,
	Email VARCHAR(50),
	CONSTRAINT User_pk PRIMARY KEY(UserID)
);

CREATE TABLE Video(
	VideoID INTEGER NOT NULL AUTO_INCREMENT,
	UserID VARCHAR(30),
	VideoTitle VARCHAR(100),
	VideoURL VARCHAR(2000),
	DateUploaded DATE
	CONSTRAINT Video_pk PRIMARY KEY(VideoID),
	CONSTRAINT Video_fk FOREIGN KEY userid_video_fk (UserID) 
		REFERENCES User(UserID)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);
